<?php

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var boolean $homePrincipal
     */
    protected $homePrincipal;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return bool
     */
    public function getHomePrincipal()
    {
        return $this->homePrincipal;
    }

    /**
     * @param $homePrincipal
     * @return $this
     */
    public function setHomePrincipal($homePrincipal)
    {
        $this->homePrincipal = $homePrincipal;
        
        return $this;
    }
}
